config/routes.rb
Rails.application.routes.draw do
  # namespace the controllers without affecting the URI
  # Login and Registration API
  post 'auth/login', to: 'authentication#authenticate'
  # post 'signup', to: 'users#create'
  root 'rentals#index'

  scope module: :v1, constraints: ApiVersion.new('v1', true) do
    
    #Users API

    post 'signup', to: 'users#create'
    # put 'users/:id', to: 'users#update'
    # get 'users/:id', to: 'users#show'

    # Rentals API
    get 'rentals', to: 'rentals#index'
    get 'rentals/activeusers', to: 'rentals#view_active_user'
    get 'rentals/checkedout', to: 'rentals#view_checked_out'
    get 'rentals/checkedactive', to: 'rentals#num_active_users_and_checked_out'
    get 'rentals/returns', to: 'rentals#pending_returns'
    get 'rentals/defaulters', to: 'rentals#pending_returns_and_defaulters'
    ####################
    get 'rentals/sendpendingemails', to: 'rentals#send_pending_emails'
    get 'rentals/sendoverdueemails',  to: 'rentals#send_overdue_emails'
    get 'rentals/listreports', to: 'rentals#list_reports'
    get 'rentals/newreport', to: 'rentals#new_report', defaults: { format: :csv }
    get 'rentals/studentbyrental/:apparel_id', to: 'rentals#getstudent'
    ####################
    get 'rentals(/:id)', to: 'rentals#show'
    ####################
    post 'rentals/assign', to: 'rentals#assign_suit'
    post 'rentals/return', to: 'rentals#return_suit'
    post 'rentals/extend/:id', to: 'rentals#extend_rental'
    ####################
    post 'rentals', to: 'rentals#create'
    put 'rentals/:id', to: 'rentals#update'
    delete 'rentals/:id', to: 'rentals#destroy'

    # Students API
    get 'students', to: 'students#index'
    get 'students(/:id)', to: 'students#show'
    post 'students', to: 'students#create'
    put  'students/:id', to: 'students#update'
    delete  'students/:id', to: 'students#destroy'
    
    # Apparels API
    get 'apparels', to: 'apparels#index'
    ###################
    get 'apparels/bysize', to: 'apparels#bysize'
    get 'apparels/bysizeandstock', to: 'apparels#bysize_and_stock'
    get 'apparels/getcheckedoutstock', to: 'apparels#get_stock', :defaults => { :stock => 1 }
    get 'apparels/getavailablestock', to: 'apparels#get_stock', :defaults => { :stock => 0 }
    get 'apparels/getsizes', to: 'apparels#get_sizes'
    ###################
    get 'apparels(/:id)', to: 'apparels#show'
    post 'apparels', to: 'apparels#create'
    put  'apparels/:id', to: 'apparels#update'
    delete  'apparels/:id', to: 'apparels#destroy'

    #Constants API
    get 'constants/getconstants', to: 'constants#show_constants'
    post 'constants/updateconstants', to: 'constants#update_constant'

    resources :constants
    resources :rentals
    resources :apparels
    resources :students
  end
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :rentals, dependent: :destroy

  validates :uin, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :phone, presence: true

  def self.by_uin(uin)
    student = Student.where(uin: uin).first
    if student == nil
      raise RecordNotFoundError.new(Response_Message::STUDENT_ENTRY_NOT_FOUND)
    end

    return student
  end

  def self.active_users
    active_id = Rental.select("student_id").where("actual_return_date is NULL")
    active_users = Student.select("
        uin, first_name as name, email,
        phone").where("id in (?)",active_id)
  end

end

app/controllers/v1/students_controller.rb
module V1
  class StudentsController < ApplicationController
    before_action :set_student, only: [:show, :edit, :update, :destroy]
	
    # GET /students
    # GET /students.json
    def index
      @students = Student.all
      json_response({success: true, data: @students}, :ok)
    end

    # GET /students/1
    # GET /students/1.json
    def show
      if @student.empty?()
        json_response({success: false, message: Message.not_found('Student record')}, :unprocessable_entity)
      else
        json_response({success: true, data: @student[0]}, :ok)
      end
    end

    # GET /students/new
    def new
      @student = Student.new
    end

    # GET /students/1/edit
    def edit
    end

    # POST /students
    # POST /students.json
    def create
      Student.create!(student_params)
      json_response({success: true, message: Message.created_successfuly('Student record')}, :created)
    end

    # PATCH/PUT /students/1
    # PATCH/PUT /students/1.json
    def update
      if @student.empty?()
        json_response({success: false, message: Message.not_found('Student record')}, :unprocessable_entity)
      else
        @student.update(student_params)
        json_response({success: true, message: Message.updated_successfuly('Student record')}, :ok)
      end
    end

    # DELETE /students/1
    # DELETE /students/1.json
    def destroy
      if @student.empty?()
        json_response({success: false, message: Message.not_found('Student record')}, :unprocessable_entity)
      else
        student_rental = Student.active_users.where(uin: params[:id])
        if !(student_rental.empty?())
          json_response({success: false, message: Message.existing_association('Student')}, :unprocessable_entity)
          return
        end

        if Student.destroy(@student.first.id)
          json_response({success: true, message: Message.destroyed_successfuly('Student record')}, :ok)
        else
          json_response({success: true, message: @student.errors}, :ok)
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_student
        @student = Student.where(:uin => params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def student_params
        params.require(:student).permit(:uin, :first_name, :last_name, :email, :phone)
      end
  end
end

app/helpers/students_helper.rb
module StudentsHelper


end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uin %>
    <%= form.number_field :uin, id: :student_uin %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :student_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :student_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :student_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :student_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/home.html.erb
<div>
  <h1>Career Closet DB demo</h1>
  <h2>
    <p>
			This page has links to students, apparels and rentals pages to demonstrate the database
    </p>
  </h2>
  <br><%= link_to "Students", students_path %></br>
  <br><%= link_to "Apparels", apparels_path %></br>
  <br><%= link_to "Rentals", rentals_path %></br>

  <h1>Developed by Hex Daemons</h1>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>UIN</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.uin %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uin:</strong>
  <%= @student.uin %>
</p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>