config/routes.rb
Rails.application.routes.draw do
  # namespace the controllers without affecting the URI
  # Login and Registration API
  post 'auth/login', to: 'authentication#authenticate'
  # post 'signup', to: 'users#create'
  root 'rentals#index'

  scope module: :v1, constraints: ApiVersion.new('v1', true) do
    
    #Users API

    post 'signup', to: 'users#create'
    # put 'users/:id', to: 'users#update'
    # get 'users/:id', to: 'users#show'

    # Rentals API
    get 'rentals', to: 'rentals#index'
    get 'rentals/activeusers', to: 'rentals#view_active_user'
    get 'rentals/checkedout', to: 'rentals#view_checked_out'
    get 'rentals/checkedactive', to: 'rentals#num_active_users_and_checked_out'
    get 'rentals/returns', to: 'rentals#pending_returns'
    get 'rentals/defaulters', to: 'rentals#pending_returns_and_defaulters'
    ####################
    get 'rentals/sendpendingemails', to: 'rentals#send_pending_emails'
    get 'rentals/sendoverdueemails',  to: 'rentals#send_overdue_emails'
    get 'rentals/listreports', to: 'rentals#list_reports'
    get 'rentals/newreport', to: 'rentals#new_report', defaults: { format: :csv }
    get 'rentals/studentbyrental/:apparel_id', to: 'rentals#getstudent'
    ####################
    get 'rentals(/:id)', to: 'rentals#show'
    ####################
    post 'rentals/assign', to: 'rentals#assign_suit'
    post 'rentals/return', to: 'rentals#return_suit'
    post 'rentals/extend/:id', to: 'rentals#extend_rental'
    ####################
    post 'rentals', to: 'rentals#create'
    put 'rentals/:id', to: 'rentals#update'
    delete 'rentals/:id', to: 'rentals#destroy'

    # Students API
    get 'students', to: 'students#index'
    get 'students(/:id)', to: 'students#show'
    post 'students', to: 'students#create'
    put  'students/:id', to: 'students#update'
    delete  'students/:id', to: 'students#destroy'
    
    # Apparels API
    get 'apparels', to: 'apparels#index'
    ###################
    get 'apparels/bysize', to: 'apparels#bysize'
    get 'apparels/bysizeandstock', to: 'apparels#bysize_and_stock'
    get 'apparels/getcheckedoutstock', to: 'apparels#get_stock', :defaults => { :stock => 1 }
    get 'apparels/getavailablestock', to: 'apparels#get_stock', :defaults => { :stock => 0 }
    get 'apparels/getsizes', to: 'apparels#get_sizes'
    ###################
    get 'apparels(/:id)', to: 'apparels#show'
    post 'apparels', to: 'apparels#create'
    put  'apparels/:id', to: 'apparels#update'
    delete  'apparels/:id', to: 'apparels#destroy'

    #Constants API
    get 'constants/getconstants', to: 'constants#show_constants'
    post 'constants/updateconstants', to: 'constants#update_constant'

    resources :constants
    resources :rentals
    resources :apparels
    resources :students
  end
end

app/models/apparel.rb
class Apparel < ApplicationRecord
  has_many :rentals, dependent: :destroy

  validates :apparel_id, presence: true, uniqueness: true

  def self.by_apparel_id(apparelId)
    apparel = Apparel.where(apparel_id: apparelId).first
    if apparel == nil
      raise RecordNotFoundError.new(Response_Message::APPAREL_ENTRY_NOT_FOUND)
    end

    return apparel
  end

  def self.view_stock(size = nil, stock = 1)
    checkedoutApparel = Rental.select("apparel_id").where("actual_return_date is NULL")
    if size == nil
      if stock == 1
        checked_out = Apparel.select("apparel_id,sex,article,size").where("id in (?)",checkedoutApparel)
      else
        checked_out = Apparel.select("apparel_id,sex,article,size").where("id not in (?)",checkedoutApparel)
      end
    else
      if stock == 1
        checked_out = Apparel.select("apparel_id,sex,article,size").where("id in (?) and apparels.size in (?)",checkedoutApparel,size)
      else
        checked_out = Apparel.select("apparel_id,sex,article,size").where("id not in (?) and apparels.size in (?)",checkedoutApparel,size)
      end
    end

    return checked_out
  end

end

app/controllers/v1/apparels_controller.rb
module V1
  class ApparelsController < ApplicationController
    before_action :set_apparel, only: [:show, :edit, :update, :destroy]

    # GET /apparels
    # GET /apparels.json
    def index
      @apparels = Apparel.all
      json_response({success: true, data: @apparels}, :ok)
    end

    def bysize
      if params[:size] != nil
        @apparels = Apparel.where("size in (?)", params[:size])
      end

      if !(@apparels.empty?())
        json_response({success: true, data: @apparels}, :ok)
      else
        json_response({success: true, message: Message.not_found()}, :unprocessable_entity)
      end  
    end

    def bysize_and_stock
      if params[:size] != nil and params[:stock] != nil
        @apparels = Apparel.view_stock(params[:size],params[:stock].to_i)
      end
        if !(@apparels.empty?())
          json_response({success: true, data: @apparels}, :ok)
        else
          json_response({success: true, message: Message.not_found()}, :unprocessable_entity)
        end
    end

    # GET /apparels/1
    # GET /apparels/1.json
    def show
      if @apparel.empty?()
        json_response({success: false, message: Message.not_found('Apparel record')}, :unprocessable_entity)
      else
        json_response({success: true, data: @apparel[0]}, :ok)
      end
    end

    # GET /apparels/new
    def new
      @apparel = Apparel.new
    end

    # GET /apparels/1/edit
    def edit
    end

    # POST /apparels
    # POST /apparels.json
    def create
      Apparel.create!(apparel_params)
      json_response({success: true, message: Message.created_successfuly('Apparel record')}, :created)
    end

    # PATCH/PUT /apparels/1
    # PATCH/PUT /apparels/1.json
    def update
      if @apparel.empty?()
        json_response({success: false, message: Message.not_found('Apparel record')}, :unprocessable_entity)
      else
        @apparel.update(apparel_params)
        json_response({success: true, message: Message.updated_successfuly('Apparel record')}, :ok)
      end
    end

    # DELETE /apparels/1
    # DELETE /apparels/1.json
    def destroy
      if @apparel.empty?()
        json_response({success: false, message: Message.not_found('Apparel record')}, :unprocessable_entity)
      else
        apparel_rental = Apparel.view_stock.where(apparel_id: params[:id])
        if !(apparel_rental.empty?())
          json_response({success: false, message: Message.existing_association('Apparel')}, :unprocessable_entity)
          return
        end

        if Apparel.destroy(@apparel.first.id)
          json_response({success: true, message: Message.destroyed_successfuly('Apparel record')}, :ok)
        else
          json_response({success: true, message: @apparel.errors}, :ok)
        end
      end
    end

    def get_sizes  
      all_sizes = Apparel.distinct.pluck('size')

      response = Hash.new()
      response['sizes'] = all_sizes
      json_response({success: true, data: response}, :ok)
    end
    
    def get_stock
      @apparels = Apparel.view_stock(nil, params[:stock].to_i)
        if !(@apparels.empty?())
          json_response({success: true, data: @apparels}, :ok)
        else
          json_response({success: true, message: Message.not_found()}, :unprocessable_entity)
        end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_apparel
        @apparel = Apparel.where(:apparel_id => params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def apparel_params
        params.require(:apparel).permit(:apparel_id, :sex, :article, :size, :notes)
      end

  end
end

app/helpers/apparels_helper.rb
module ApparelsHelper
end

app/views/apparels/_form.html.erb
<%= form_with(model: apparel, local: true) do |form| %>
  <% if apparel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apparel.errors.count, "error") %> prohibited this apparel from being saved:</h2>

      <ul>
      <% apparel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :apparel_id %>
    <%= form.text_field :apparel_id, id: :apparel_apparel_id %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :apparel_sex %>
  </div>

  <div class="field">
    <%= form.label :article %>
    <%= form.text_field :article, id: :apparel_article %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :apparel_size %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes, id: :apparel_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apparels/edit.html.erb
<h1>Editing Apparel</h1>

<%= render 'form', apparel: @apparel %>

<%= link_to 'Show', @apparel %> |
<%= link_to 'Back', apparels_path %>

app/views/apparels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apparels</h1>
<%=form_tag apparels_path, :method => :get do %>
  <%- @all_sizes.each do |size| %>
    <%= size %>
    <%= check_box_tag "size[]",size %>
    <% end %>
<%= submit_tag 'Filter' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Apparel</th>
      <th>Sex</th>
      <th>Article</th>
      <th>Size</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apparels.each do |apparel| %>
      <tr>
        <td><%= apparel.apparel_id %></td>
        <td><%= apparel.sex %></td>
        <td><%= apparel.article %></td>
        <td><%= apparel.size %></td>
        <td><%= apparel.notes %></td>
        <td><%= link_to 'Show', apparel %></td>
        <td><%= link_to 'Edit', edit_apparel_path(apparel) %></td>
        <td><%= link_to 'Destroy', apparel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apparel', new_apparel_path %>

app/views/apparels/new.html.erb
<h1>New Apparel</h1>

<%= render 'form', apparel: @apparel %>

<%= link_to 'Back', apparels_path %>

app/views/apparels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apparel:</strong>
  <%= @apparel.apparel_id %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @apparel.sex %>
</p>

<p>
  <strong>Article:</strong>
  <%= @apparel.article %>
</p>

<p>
  <strong>Size:</strong>
  <%= @apparel.size %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @apparel.notes %>
</p>

<%= link_to 'Edit', edit_apparel_path(@apparel) %> |
<%= link_to 'Back', apparels_path %>