config/routes.rb
Rails.application.routes.draw do
  # namespace the controllers without affecting the URI
  # Login and Registration API
  post 'auth/login', to: 'authentication#authenticate'
  # post 'signup', to: 'users#create'
  root 'rentals#index'

  scope module: :v1, constraints: ApiVersion.new('v1', true) do
    
    #Users API

    post 'signup', to: 'users#create'
    # put 'users/:id', to: 'users#update'
    # get 'users/:id', to: 'users#show'

    # Rentals API
    get 'rentals', to: 'rentals#index'
    get 'rentals/activeusers', to: 'rentals#view_active_user'
    get 'rentals/checkedout', to: 'rentals#view_checked_out'
    get 'rentals/checkedactive', to: 'rentals#num_active_users_and_checked_out'
    get 'rentals/returns', to: 'rentals#pending_returns'
    get 'rentals/defaulters', to: 'rentals#pending_returns_and_defaulters'
    ####################
    get 'rentals/sendpendingemails', to: 'rentals#send_pending_emails'
    get 'rentals/sendoverdueemails',  to: 'rentals#send_overdue_emails'
    get 'rentals/listreports', to: 'rentals#list_reports'
    get 'rentals/newreport', to: 'rentals#new_report', defaults: { format: :csv }
    get 'rentals/studentbyrental/:apparel_id', to: 'rentals#getstudent'
    ####################
    get 'rentals(/:id)', to: 'rentals#show'
    ####################
    post 'rentals/assign', to: 'rentals#assign_suit'
    post 'rentals/return', to: 'rentals#return_suit'
    post 'rentals/extend/:id', to: 'rentals#extend_rental'
    ####################
    post 'rentals', to: 'rentals#create'
    put 'rentals/:id', to: 'rentals#update'
    delete 'rentals/:id', to: 'rentals#destroy'

    # Students API
    get 'students', to: 'students#index'
    get 'students(/:id)', to: 'students#show'
    post 'students', to: 'students#create'
    put  'students/:id', to: 'students#update'
    delete  'students/:id', to: 'students#destroy'
    
    # Apparels API
    get 'apparels', to: 'apparels#index'
    ###################
    get 'apparels/bysize', to: 'apparels#bysize'
    get 'apparels/bysizeandstock', to: 'apparels#bysize_and_stock'
    get 'apparels/getcheckedoutstock', to: 'apparels#get_stock', :defaults => { :stock => 1 }
    get 'apparels/getavailablestock', to: 'apparels#get_stock', :defaults => { :stock => 0 }
    get 'apparels/getsizes', to: 'apparels#get_sizes'
    ###################
    get 'apparels(/:id)', to: 'apparels#show'
    post 'apparels', to: 'apparels#create'
    put  'apparels/:id', to: 'apparels#update'
    delete  'apparels/:id', to: 'apparels#destroy'

    #Constants API
    get 'constants/getconstants', to: 'constants#show_constants'
    post 'constants/updateconstants', to: 'constants#update_constant'

    resources :constants
    resources :rentals
    resources :apparels
    resources :students
  end
end

app/models/constant.rb
class Constant < ApplicationRecord
  validates :key, presence: true, uniqueness: true

  def self.find_value(key)
    Constant.where(key: key).first.value
  end
end

app/controllers/v1/constants_controller.rb
module V1
  class ConstantsController < ApplicationController
    before_action :set_constant, only: [:show, :edit, :update, :destroy]

    # GET /constants
    # GET /constants.json
    def index
      @constants = Constant.all
    end

    # GET /constants/1
    # GET /constants/1.json
    def show
    end

    # GET /constants/new
    def new
      @constant = Constant.new
    end

    # GET /constants/1/edit
    def edit
    end

    # POST /constants
    # POST /constants.json
    def create
      @constant = Constant.new(constant_params)

      respond_to do |format|
        if @constant.save
          format.html { redirect_to @constant, notice: 'Constant was successfully created.' }
          format.json { render :show, status: :created, location: @constant }
        else
          format.html { render :new }
          format.json { render json: @constant.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /constants/1
    # PATCH/PUT /constants/1.json
    def update
      respond_to do |format|
        if @constant.update(constant_params)
          format.html { redirect_to @constant, notice: 'Constant was successfully updated.' }
          format.json { render :show, status: :ok, location: @constant }
        else
          format.html { render :edit }
          format.json { render json: @constant.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /constants/1
    # DELETE /constants/1.json
    def destroy
      @constant.destroy
      respond_to do |format|
        format.html { redirect_to constants_url, notice: 'Constant was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def show_constants
      constants = Constant.all
      json_response({success: true, data: constants}, :ok)
    end

    def update_constant
      @constant = Constant.where(key: params[:key]).first
      if @constant.update(value: params[:value])
        json_response({success: true, message: Message.success_response}, :ok)
      else
        json_response({success:false, message: @constant.errors}, :internal_server_error)
      end
    end

    def createResponseMessage(statusCode,statusMessage)
      response=Hash.new()
      response["statusCode"]=statusCode
      response["statusMessage"]=statusMessage
      return response
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_constant
        @constant = Constant.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def constant_params
        params.require(:constant).permit(:key, :value, :created, :updated)
      end
  end
end

app/helpers/constants_helper.rb
module ConstantsHelper
end

app/views/constants/_form.html.erb
<%= form_with(model: constant, local: true) do |form| %>
  <% if constant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(constant.errors.count, "error") %> prohibited this constant from being saved:</h2>

      <ul>
      <% constant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key, id: :constant_key %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :constant_value %>
  </div>

  <div class="field">
    <%= form.label :created %>
    <%= form.datetime_select :created, id: :constant_created %>
  </div>

  <div class="field">
    <%= form.label :updated %>
    <%= form.datetime_select :updated, id: :constant_updated %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/constants/edit.html.erb
<h1>Editing Constant</h1>

<%= render 'form', constant: @constant %>

<%= link_to 'Show', @constant %> |
<%= link_to 'Back', constants_path %>

app/views/constants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Constants</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constants.each do |constant| %>
      <tr>
        <td><%= constant.key %></td>
        <td><%= constant.value %></td>
        <td><%= constant.created %></td>
        <td><%= constant.updated %></td>
        <td><%= link_to 'Show', constant %></td>
        <td><%= link_to 'Edit', edit_constant_path(constant) %></td>
        <td><%= link_to 'Destroy', constant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constant', new_constant_path %>

app/views/constants/new.html.erb
<h1>New Constant</h1>

<%= render 'form', constant: @constant %>

<%= link_to 'Back', constants_path %>

app/views/constants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @constant.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @constant.value %>
</p>

<p>
  <strong>Created:</strong>
  <%= @constant.created %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @constant.updated %>
</p>

<%= link_to 'Edit', edit_constant_path(@constant) %> |
<%= link_to 'Back', constants_path %>